[alembic]
script_location = alembic
# sqlalchemy.url = driver://user:pass@localhost/dbname
sqlalchemy.url = postgresql://username:password@localhost/chat_db
# Uncomment to use the following options
# timezone = UTC
# file_template = %%(rev)s_%%(slug)s
# revision_environment = true

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args =
level = DEBUG
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-8s %(message)s
datefmt = %Y-%m-%d %H:%M:%S